### ISSUE TITLE
When removing parameters one cannot scroll or see all parameters.

### ISSUE THREAD

**Issue by Pedrotheplant** [nikobojs/manuscrape_electron#49]
Is it possible to have a scroll function so that one can see all parameters when clicking "remove parameter"?

**Comment by nikobojs** [comment]
I think the issue is , that the input field works more like a search than a dropdown. Will try looking at the UI/UX at some point and see if I can come up with something.

You should be able to search for the field and find it, even though its not displayed on the list in the beginning. Right? :sweat_smile:

**Comment by Pedrotheplant** [comment]
Yes, the search function is awesome! Let's keep it that way :)

**Comment by nikobojs** [comment]
I fixed it. The result will now show all the fields unless you are searching :+1:
