### ISSUE TITLE
Can't add new field to existing project from manuscrape.org

### ISSUE THREAD

**Issue by Mod-lab-stoff** [nikobojs/manuscrape_electron#53]
i tried to add a dropdown or text field to an existing project in firefox and got " unexpected server error".

**Comment by nikobojs** [comment]
I can't reproduce this error and have no clue how to. Can you provide some more details? And maybe invite me to the project temporarily on n at nikobojs dot com.

**Comment by Mod-lab-stoff** [comment]
Just tried again in firefox and edge, same error.
You have now been invited

![image](https://github.com/nikobojs/manuscrape_electron/assets/149067130/3d6ee328-da91-4e4f-adde-319206f76c5e)

**Comment by nikobojs** [comment]
I reproduced the bug :+1: It seems the unique constraints in the database are blocking the request. Will research deeper and hopefully fix within an hour

**Comment by nikobojs** [comment]
It was due to bad logic in the parameter index system (the order of project parameters).

I have refactored the index logic and added automation of correcting invalid parameter indexes. So from on, it should work and correct itself automagically for all occurrences of wrong parameter index values.

Give it a try and see if it works!

**Comment by Mod-lab-stoff** [comment]
It works now thanks!
