### ISSUE TITLE
Display the observation ID no. in the draft window

### ISSUE THREAD

**Issue by Pedrotheplant** [nikobojs/manuscrape_electron#84]
It would be nice to have the ID number displayed in the draft window. Occasionally I need to write a note somewhere that relates to the ID number before the draft is done or need review a draft as project owner before it is published. Having an ID-number would make this easier.

**Comment by nikobojs** [comment]
Fixed in https://github.com/nikobojs/manuscrape_nuxt/commit/c73b83f94889c60be427475688a008081e00439f (see screenshot).

Will be released soon :-) Marking as solved
![Screenshot from 2024-05-02 13-08-04](https://github.com/nikobojs/manuscrape_electron/assets/22896724/961819a4-6639-46a6-b458-d8d8cf35daaf)
