### ISSUE TITLE
"Econnreset" message when creating draft

### ISSUE THREAD

**Issue by tvg112** [nikobojs/manuscrape_electron#93]
The ManuScrape application is running on my computer, but when I try to create a draft with a screenshot, I get the 'ECONNRESET' error message in the bottom corner after the screenshot is taken. The draft is still created, but without the picture.

![Skærmbillede 2024-10-23 101437](https://github.com/user-attachments/assets/0dd8cab8-ae51-48e6-971c-20b04784db20)

**Comment by nikobojs** [comment]
This is because TDC had an unexpected outage around 10-11 AM in Copenhagen :face_with_diagonal_mouth:  It should be up and running again. I will keep this issue open as the error was not handled very smoothly.

Thanks for the issue :pray:

**Comment by oscwa** [comment]
Hello! Just letting you know that the issue still persists at 07:30 today (24/10). 
Best, Oscar

**Comment by nikobojs** [comment]
All right. I successfully recreated the bug. Looking into fixing it now. Hopefully it wont take long :crossed_fingers:

Thanks for the follow-up Oscar :pray:

**Comment by nikobojs** [comment]
I'm sorry to keep you waiting. I have fixed the bug locally. And will create a new manuscrape release, which you'll need to install.

It seems that our dependency `axios` is terrible at sending multipart requests (image upload in this case).

The weird thing is that it has worked for more than a year. Another weird thing is that the only place we use `axios` in the whole application is exactly where it fails now. I still don't know why this error did not happen before :sweat_smile: 

A curious case of not knowing why it works AND why it does not work...

Anyway, it will require a release, which takes some time as well. I'll keep this thread updated.

UPDATE: I found out what the problem was. It was not related to `axios` but a new user-agent based firewall rule I had set on the server :crying_cat_face:

**Comment by nikobojs** [comment]
The patched version 1.0.8 is finally ready: https://github.com/nikobojs/manuscrape_electron/releases/tag/1.0.8
Please give it a shot and let me know how it goes 🙏

**Comment by oscwa** [comment]
I finally got around to try out the patched version. It works perfectly so far. Thanks Nikolaj!

**Comment by nikobojs** [comment]
No problem ! Enjoy your day :smile:
