### ISSUE TITLE
Automatic version checking and alerting in native app

### ISSUE THREAD

**Issue by Pedrotheplant** [nikobojs/manuscrape_electron#94]
When taking new screenshot I get the above error code. It creates a new observation ID, but does not take a screenshot. when I try to add the imagefile manually afterwards the program freezes.

**Comment by nikobojs** [comment]
This error is fixed by upgrading to the newest version of ManuScrape. Many people get this error, and don't know what to do. It indicates we need automatic version checking so people get alerts in their OS when a new version is available. I will change the title of the issue to indicate that.

Original title: "Screenshot function error: "ECONNRESET"

**Comment by nikobojs** [comment]
The next version has a version-check feature, which will slowly be migrated into manuscrape in the next couple of releases.
